stages:
  - publish
  - deliver

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

deliver:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "gcs-snapshot" "0.1"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - .gitlab-ci.yml
      - docker-compose.yml
      - ci/docker-deliver.sh
      - Dockerfile
      - src/*
      - requirements.txt
  tags:
    - imagesbuilder
